name: Demo Push

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Define Image Name
        run: |
          IMAGE_BASE=$(echo ghcr.io/${{ github.repository_owner }}/portfolio-simon | tr '[:upper:]' '[:lower:]')
          TIMESTAMP=$(date +%s)
          echo "IMAGE_NAME=$IMAGE_BASE:$TIMESTAMP" >> $GITHUB_ENV
          echo "IMAGE_LATEST=$IMAGE_BASE:latest" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }} --label "runnumber=${GITHUB_RUN_ID}"
          docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_LATEST }}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker push ${{ env.IMAGE_NAME }}
          docker push ${{ env.IMAGE_LATEST }}

      - name: Update Kubernetes deployment
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://github.com/SimonGallien/portfolio-simon-k3s.git
          cd portfolio-simon-k3s
          
          echo "Before update:"
          cat deployments/deployment.yaml | grep "image:"

          # Forcer un changement même si l'image est déjà latest
          sed -i 's|image: ghcr.io/simongallien/portfolio-simon:.*|image: ghcr.io/simongallien/portfolio-simon:latest|' deployments/deployment.yaml
          touch deployments/deployment.yaml

          echo "After update:"
          cat deployments/deployment.yaml | grep "image:"

          git add deployments/deployment.yaml
          git commit -m "Auto-update image to latest" --allow-empty
          git push https://x-access-token:${{ secrets.GHCR_PAT }}@github.com/SimonGallien/portfolio-simon-k3s.git main
  
