#
name: Demo Push

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Define Image Name
        run: echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/portfolio-simon:$(date +%s)" >> $GITHUB_ENV

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }} --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          echo "Pushing image: ${{ env.IMAGE_NAME }}"
          docker push ${{ env.IMAGE_NAME }}

      - name: Update Kubernetes deployment
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://github.com/SimonGallien/portfolio-simon-k3s.git
          cd portfolio-simon-k3s
          sed -i 's|image: ghcr.io/SimonGallien/portfolio-simon:.*|image: ${{ env.IMAGE_NAME }}|' deployments/deployment.yaml
          git add deployments/deployment.yaml
          git commit -m "Auto-update image to latest"
          git push https://x-access-token:${{ secrets.GHCR_PAT }}@github.com/SimonGallien/portfolio-simon-k3s.git main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
